OHS-Hosting-Infrastructure/complaint-tracker

app/views/application/_header.html.erb
Previously, the USWDS banner would expand after the user logs out, instead of remaining collapsed.
After this change, the USWDS banner remains collapsed until the user expands it.
1. Login with an HSES user account
2. Logout
3. Verify that the USWDS banner remains collapsed
* closes #43 
- no current tests around UI like this.
- boundary diagram doesnt yet exist
* **praise:**
* **nitpick:**
* **issue:**
* **thought:**
* **chore:**
=> Keep USWDS banner collapsed after logout

Gemfile, Gemfile.lock, app/controllers/complaints_controller.rb, app/lib/fake_data/complaints.rb, spec/lib/fake_data/complaints_spec.rb
Adds mocked in data imitating future HSES response
Addresses: https://github.com/OHS-Hosting-Infrastructure/complaint-tracker/issues/49
`rails spec` runs a couple cursory tests which check the basic structure of the data being created
If you want to look at the data being generated, you can add `<%= @complaints.to_json %>` to `app/views/complaints/index.html.erb`
- closes #49
- moved to "in progress"
- for reviewers: do you think this is enough testing?
- ~[ ] API Documentation updated~
- ~[ ] Boundary diagram updated~
- ~[ ] Logical Data Model updated~
- for reviewers: should I make an ADR explaining why we went with ffaker instead of the staging export data?
This project is using [Conventional Comments](https://conventionalcomments.org/) to give …
=> Complaints fake data

app/views/application/_header.html.erb
Increases the font size of the text in the header to meet #62 
The font size of the header is closer to 32 than it is to 22.
Check out the branch, inspect the text in the header, check in the computed CSS
* closes #62
- ~[Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions~
I have questions:
- Is it okay that the page's `<h1>` is 39px?
- Is that USWDS class the best one to apply to accomplish this?
* **praise:**
* **nitpick:**
* …
=> increases header size to 31.2px

.github/workflows/pa11y.yml
* Get error code for pa11y scan directly from the exit status code instead of parsing the output
* Only comment on PRs when the scan fails.
Paired with @jduss4 for this work
* A failing scan causes the build status to be failed, and outputs the information to a PR comment
* A passing scan does not add a PR comment.
Check CI/CD output
* closes #55 
~- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)~
No UI changes
~- [ ] API Documentation updated~
No APIs updated
~- [ ] Boundary diagram updated~
No boundary updates
~- [ ] Logical Data Model updated~
LDM doesn't yet exist
~- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions~
no major decisions made
This project is using [Conventional …
=> Ensure pa11y scans fail the build when they fail

app/controllers/sessions_controller.rb, app/views/layouts/_flash_messages.html.erb, app/views/layouts/application.html.erb, spec/requests/complaints_spec.rb, spec/views/application/_flash_messages.html.erb_spec.rb
Displays a message to the user after logging out. Adds flash notice / error to layout for future use.
Log in, then log out. You should see a message in green with a checkbox near the top of the page confirming you are now logged out.
* closes #51
- ~Architectural Decision Records~
* **praise:**
* **nitpick:**
* **issue:**
* **thought:**
* **chore:**
=> displays message confirming log out

.github/workflows/pa11y.yml, .pa11yci, README.md, app/controllers/application_controller.rb, app/controllers/complaints_controller.rb, app/controllers/pages_controller.rb, app/controllers/sessions_controller.rb, app/views/complaints/index.html.erb, app/views/layouts/_flash_messages.html.erb, app/views/pages/welcome.html.erb, config/routes.rb, spec/requests/complaints_spec.rb, spec/requests/pages_spec.rb, spec/views/application/_flash_messages.html.erb_spec.rb
* Enables setting a `BYPASS_AUTH` flag to allow pa11y to scan the complaints table
Given I'm running a pa11y scan
When an error is in place on the complaint table
Then the scan should fail
1. Update one of the table cells in `_complaints_table.html.erb` to have `style="color: #eee;"`
2. Run the server with `RAILS_ENV=test BYPASS_AUTH=true bundle exec rails server`
3. Run pa11y with: `yarn run pa11y-ci`
You should see color contrast failures on http://localhost:8080/complaints
* closes #76 
* closes #8 I think, since this can be used in any non-production environment. It doesn't quite pass the AC there though
and context to PR comments. Please use these …
=> Pa11y scan for logged in pages

app/controllers/complaints_controller.rb, app/models/fake_data/api_response.rb, spec/models/api_response_spec.rb, spec/requests/complaints_spec.rb
Adds a class variable to the ComplaintsController which contains the fake data. This way, the fake data will not change when the user refreshes the page or navigates between (future) complaints pages.
The fake data does not change on every request or between users, just on app reload.
Manually, can start up the app and refresh the index page a few times to verify that the fake data is not changing. In terms of how to test the data is persistent in rspec, I am seeking advice.
* closes https://github.com/OHS-Hosting-Infrastructure/complaint-tracker/issues/79
- ~Meets accessibility standards (WCAG 2.1 Levels A, AA)~
- ~[Architectural Decision …
=> Adds class variable to controller to persist fake issues data

app/helpers/complaints_helper.rb, app/models/fake_data/complaint.rb, app/views/complaints/_complaints_table.html.erb, app/views/complaints/_complaints_table_detail.html.erb, spec/helpers/complaints_helper_spec.rb, spec/views/complaints/_complaints_table.html.erb_spec.rb, spec/views/complaints/_complaints_table_detail.html.erb_spec.rb
This change adds the formatted status to the complaints table view.
It also creates a sort order as described in the linked issue so a user can sort based on status. (So new complaints rise to the top)
Given that I am a Program Specialist
When I click on the status column of my complaints list
Then I see the status of complaints listed in the status column as:
"New"
"Rec. Reopening"
"Reopened"
"In Progress"
"Rec. Closure"
"Closed"
note: this PR does not address the colors that might be mentioned in #71 -- those have been separated out into #81
* closes #71 
* **praise:**
* **nitpick:**
* …
=> Add sortable complaint status

LICENSE.md, doc/adr/0005-license.md
Adds a CC0 (public domain) license. I took this directly from the license used by the (deprecated) [18F open source styleguide](https://github.com/18F/open-source-guide/blob/18f-pages/LICENSE.md).
`LICENSE.md` explains the terms of our license and links out to the CC0 legal text
Look at `LICENSE.md`, I guess
* closes https://github.com/OHS-Hosting-Infrastructure/complaint-tracker/issues/67
- ~[Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions~
* **praise:**
* **nitpick:**
* **issue:**
* **thought:**
* …
=> adds CC0 license

app/controllers/sessions_controller.rb, app/views/layouts/_flash_messages.html.erb, spec/requests/complaints_spec.rb
Implements Laura's design for log out notice which alerts user to discrepancy between login status of complaints tracker vs HSES
Message with new text appears to user with return line and italics on logout
Run app locally. Log in or BYPASS_AUTH, then click log out button. You should see message towards top of the screen.
* closes https://github.com/OHS-Hosting-Infrastructure/complaint-tracker/issues/69
- ~[Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions~
and context to PR comments. Please use these labels in your …
=> expands upon log out message to explain HSES status

.github/workflows/deploy-stage.yml, .github/workflows/terraform-stage.yml, terraform/README.md, terraform/stage/providers.tf
Creates 2 GitHub Action jobs:
- runs `terraform plan` when a PR to the main branch is opened, and outputs the results of `terraform plan` to a comment. Should fail if `terraform plan` fails
- runs `terraform apply` when changes to the terraform staging and shared directories are made and pushed to the main branch
At least I hope that's what happens, because I don't know how to test the second one.
- `terraform plan` outputs content to a PR issue
- `terraform apply` runs successfully on main branch (not sure how to test this?)
Great question!  I don't recommend the `act` library, unfortunately. I've tested manually here, so hopefully this PR getting a successful comment is enough evidence for the first goal of this PR.
* closes https://github.com/OHS-Hosting-Infrastructure/complaint-tracker …
=> Terraform actions

app/helpers/complaints_helper.rb, app/views/complaints/_complaints_table.html.erb, app/views/complaints/_complaints_table_detail.html.erb, spec/helpers/complaints_helper_spec.rb, spec/views/complaints/_complaints_table_detail.html.erb_spec.rb
The fake data structure changed, but the frontend wasn't adapted to fit it (my bad), so summary and status fell off the UI. This fixes that, by grabbing the identifier from the fake data's status and changing the name "issue" -> "summary".
The FORMATTED_STATUS does not match the labels in the HSES response, but that is expected, and we prefer the formatted status labels. For this reason, I am not passing the fake data's status label straight through to the user.
You can view status and summary on the complaints index page.
Fire up rails and check out the complaints page.
- ~[ ] No issue created~
and context to PR comments. Please use these labels in your …
=> fixes fake data on complaints page

app/models/api.rb, config/environments/ci.rb, spec/models/api_spec.rb
Prevents `ci` environment from using any HSES endpoints / auth for staging information. This is for the following reasons:
- HSES would not recognize the IP of a request sent during the CI process
- Tools like pa11y do not need real data at this point to function
- application functions in `ci` environment and uses fake data
Start app with `RAILS_ENV=ci rails s` to confirm
* closes https://github.com/OHS-Hosting-Infrastructure/complaint-tracker/issues/136
- ~Meets accessibility standards (WCAG 2.1 Levels A, AA)~
- ~[Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions~
This project is using [Conventional …
=> swaps out ci environment so it will use fake data

app/views/complaints/_complaints_table.html.erb, app/views/complaints/show.html.erb, spec/requests/complaints_spec.rb, spec/views/complaints/_complaints_table.html.erb_spec.rb, spec/views/complaints/show.html.erb_spec.rb
- Update Issue header
As an authorized user
When I view a complaint
I want to see "HSES Issue #"
`bundle exec rake spec`
* closes #152 
* **praise:**
* **nitpick:**
* **issue:**
* **thought:**
* **chore:**
=> HSES issue number

app/models/api/fake_data/grantee.rb, app/models/api/hses.rb, app/models/grant.rb, app/models/grantee.rb, app/views/grantees/show.html.erb, spec/models/api/fake_data/grantee_spec.rb, spec/models/grant_spec.rb, spec/models/grantee_spec.rb, spec/views/grantees/show.html.erb_spec.rb
Wiring in grantee data
This required an update of the FakeData model, as it was making incorrect assumptions.
The grantee detail page still works
* **praise:**
* **nitpick:**
* **issue:**
* **thought:**
* **chore:**
=> Wire up grantee data

app/helpers/complaints_helper.rb, app/models/complaint.rb, app/views/complaints/_complaints_table.html.erb, app/views/complaints/_complaints_table_detail.html.erb, app/views/complaints/show.html.erb, spec/helpers/complaints_helper_spec.rb, spec/models/complaint_spec.rb, spec/models/monitoring_review_spec.rb, spec/views/complaints/_complaints_table_detail.html.erb_spec.rb
I went to add "Yes" to the RAN and TTA columns of the index page's complaint table, when I decided it would be much easier if the Complaint model itself knew whether it had any RAN / TTA activity.  Then I realized heck, it would be great if it knew if it was a new complaint, and if it could return its status already formatted and then I kinda just kept redoing things....
- moves formatted status behavior out of helpers, simplifies views
- adds methods for `new?`, `has_monitoring_review?`, and `has_tta_report?`
In terms of the RAN / TTA issue, this is what I've got:
- are these helpful and logical changes?
- nothing got broken along the way (like status formatting / sorting)
- RAN and TTA have "Yes" if the issue is linked to something
Start the app, navigate to a complaint page and add a …
=> changes table detail to use complaint model and adds RAN / TTA activity

app/helpers/complaints_helper.rb, app/views/complaints/_complaints_table.html.erb, app/views/complaints/_pagination.html.erb, spec/helpers/complaints_helper_spec.rb, spec/views/complaints/_pagination.erb_spec.rb
Adds sort to the pagination links so we can access the second page of oldest issues
Sort issues by oldest first
Click on link to page 2
Should see second-oldest page of issues
* closes #229 
* **praise:**
* **nitpick:**
* **issue:**
* **thought:**
* **chore:**
=> Add sort variable to pagination links

app/models/complaint.rb, app/views/complaints/show.html.erb, spec/views/complaints/show.html.erb_spec.rb
Adds link to grantee name on complaint detail page for grantee detail page.
NOTE: uses agencyId, not grantNumber for the identifier in the URL
- is a link
- works
Navigate to a complaint detail page, click the grantee name in the summary box, go to a real place.
I recommend testing this with real data, but fake data should at least get you somewhere.
* closes #232 
* **praise:**
* **nitpick:**
* **issue:**
* **thought:**
* **chore:**
=> adds link for grantee on complaint detail page

app/controllers/issue_monitoring_reviews_controller.rb, app/javascript/packs/complaint-links.js, app/views/complaints/_issue_monitoring_review.html.erb, app/views/complaints/_issue_tta_report.html.erb, app/views/complaints/_monitoring_edit_review.html.erb, app/views/complaints/_tta_edit_activity_report.html.erb, app/views/complaints/show.html.erb, spec/features/complaints/monitoring_review_spec.rb, spec/features/complaints/tta_activity_report_spec.rb, spec/views/complaints/show.html.erb_spec.rb
Adds editing functionality to the monitoring link on a complaint detail page.  Ideal error functionality was not in this issue, but can be done as part of #207 if we get there.
- can edit a linked review
Go to a complaint detail page, choose an existing linked review (or add one if there isn't anything already), click the pencil icon, change the number, check that it saved correctly!
* closes #228 
* **praise:**
* **nitpick:**
* **issue:**
* **thought:**
* **chore:**
=> Edit ran link

app/models/api/monitoring.rb
We do not have an endpoint set up with IT-AMS to send actual monitoring requests, so currently requests should be relying on a fake review. Unfortunately, this class had drifted from the fake monitoring data. This commit lines up its class type and how it calls the fake data.
Able to add a RAN review to a complaint detail page when using `CT_USE_REAL_API_DATA=true`
See above
* part of #236 
* **praise:**
* **nitpick:**
* **issue:**
* **thought:**
* **chore:**
=> aligns "real" monitoring request with faked request

app/models/tta_activity_report.rb, spec/features/complaints/tta_activity_report_spec.rb, spec/models/api/fake_data/activity_report_spec.rb, spec/models/api/fake_data/tta_spec.rb, spec/models/timeline/tta_event_spec.rb, spec/models/timeline_spec.rb, spec/requests/issue_tta_reports_spec.rb
Adds some validation around the TTA Display ID format because TTAHub 500s if the display id is not in the expected format.
When I input a TTA Activity Report Display ID that does not match the format `/^R/d{2}-AR-/`
I want an error that tells me it's a bad format
So I know what the problem is
* **praise:**
* **nitpick:**
* **issue:**
* **thought:**
* **chore:**
=> Add validation for Display Id format

app/views/grantees/show.html.erb, spec/views/grantees/show.html.erb_spec.rb
we have not implemented this and will not be before the demo
removes the "Open Issues" summary section on the grantee detail page
you can go look at the grantee page, and it should be gone
Not related to an issue
* **praise:**
* **nitpick:**
* **issue:**
* **thought:**
* **chore:**
=> removes unused portion of grantee page
